# Generated by Django 5.0.3 on 2024-03-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modified',
            new_name='modified_date',
        ),
    ]
